<?php 
/*
软件著作权：=====================================================
软件名称：兴奥国际物流转运网站管理系统(简称：兴奥转运系统)V7.0
著作权人：广西兴奥网络科技有限责任公司
软件登记号：2016SR041223
网址：www.xingaowl.com
本系统已在中华人民共和国国家版权局注册，著作权受法律及国际公约保护！
版权所有，未购买严禁使用，未经书面许可严禁开发衍生品，违反将追究法律责任！
*/
require_once($_SERVER['DOCUMENT_ROOT'].'/public/config_top.php');
require_once($_SERVER['DOCUMENT_ROOT'].'/public/function.php');

$userid=$_SESSION['member']['userid'];
if(!$userid){
//if(!$_COOKIE['member_cookie']){
	//header("location:/m2/user/login.php");
	header("location:/xamember/");
	exit;
}
require_once($_SERVER['DOCUMENT_ROOT']."/m/html/index{$LT}.html");//载入默认首页
?>